-- جدول شرائح المدن السحابية: يتحكم بمدن السلايدر وصورها من السحابة
-- (تُحدَّث من حين لآخر عبر التخزين/القاعدة دون إعادة بناء التطبيق).
create table if not exists public.city_slides (
  id bigint generated by default as identity primary key,
  "order" integer not null default 0,
  name_ar text not null,
  name_en text not null,
  image_url text,
  created_at timestamptz not null default now()
);

-- قراءة عامة (بدون مصادقة) لأي عميل.
alter table public.city_slides enable row level security;

drop policy if exists "city_slides public read" on public.city_slides;
create policy "city_slides public read"
  on public.city_slides for select
  using (true);

-- دلو تخزين عام لصور المدن (ارفع الصور/الـ GIF هنا).
insert into storage.buckets (id, name, public)
values ('city-images', 'city-images', true)
on conflict (id) do nothing;

-- ملاحظة أمان: لا ننشئ سياسة SELECT على storage.objects لأن الدلو عام،
-- فتُقدَّم الملفات عبر الرابط العام (object/public/...) مباشرة دون الحاجة إلى
-- سياسة تجعل العملاء قادرين على جلب قائمة بكل الملفات. (لا يصح تجاوز هذا التحذير).

-- بذور افتراضية (بدون رابط فيتطابق التطبيق على الصور المحلية حتى ترفع صورك).
insert into public.city_slides ("order", name_ar, name_en, image_url) values
  (0, 'صنعاء', 'Sanaa', null),
  (1, 'عدن', 'Aden', null),
  (2, 'تعز', 'Taiz', null),
  (3, 'الحديدة', 'Hodeidah', null),
  (4, 'إب', 'Ibb', null),
  (5, 'المكلا', 'Mukalla', null)
on conflict do nothing;

-- لاحقاً (لفّ رابطاً سحابياً) مثلاً:
-- update public.city_slides
--   set image_url = 'https://lgkexjmtzmcwfbkockwj.supabase.co/storage/v1/object/public/city-images/sanaa.gif'
--   where name_ar = 'صنعاء';
